name: ðŸŒ Web Builds
on:
  workflow_call:
    inputs:
      release:
        required: true
        type: boolean
      version:
        required: true
        type: string
      version_ref:
        description: "Godot engine commit reference"
        required: true
        type: string

# Global Settings
env:
  # 4.4
  SCONSFLAGS: >-
    debug_symbols=no
    use_closure_compiler=yes
    strict_checks=yes
    deprecated=no
    lto=none
    use_assertions=no
    use_safe_heap=yes
  # 4.5+
  # Ideally we'd use dev_mode=yes. Unfortunately, v8 headers contain warnings. So we manually set some dev_mode options.
  SCONS_FLAGS: >-
    verbose=yes
    warnings=extra
    strict_checks=yes
    tests=no
    debug_symbols=no
    use_closure_compiler=yes

jobs:
  web-template:
    runs-on: ubuntu-24.04
    name: Web (${{ matrix.target }}, ${{ matrix.engine }}, threads=${{ matrix.threads }}, dlink=${{ matrix.dlink }})
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        engine: [ browser, qjs-ng ]
        target: ${{ inputs.release && fromJSON('["template_release","template_debug"]') || fromJSON('["template_debug"]') }}
        threads: ${{ inputs.release && fromJSON('["yes","no"]') || fromJSON('["yes"]') }}
        dlink: ${{ inputs.release && fromJSON('["yes","no"]') || fromJSON('["no"]') }}
    steps:
      - name: ðŸ§¬ Generate Name
        id: name
        run: |
          echo "name=web${{ matrix.dlink == 'yes' && '-dlink' || '' }}${{ matrix.threads == 'no' && '-nothreads' || '' }}-${{ matrix.target }}-${{inputs.version}}-${{ matrix.engine }}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Checkout Godot
        uses: actions/checkout@v4
        with:
          repository: godotengine/godot
          ref: ${{ inputs.version_ref }}
          submodules: recursive

      - name: Checkout GodotJS
        uses: actions/checkout@v4
        with:
          path: ${{github.workspace}}/modules/GodotJS/
          lfs: true
          submodules: recursive

      - name: Download scripts/out
        uses: actions/download-artifact@v4
        with:
          name: scripts-out
          path: ${{github.workspace}}/modules/GodotJS/scripts/out

      - name: Download impl/web/js
        if: matrix.engine == 'browser'
        uses: actions/download-artifact@v4
        with:
          name: impl-web-js
          path: ${{github.workspace}}/modules/GodotJS/impl/web/js

      - name: Determine Emscripten version
        id: versions
        env:
          GODOT_VERSION: ${{ inputs.version }}
        run: |
          if [[ $GODOT_VERSION == "4.4" ]]; then
            echo "emscripten=3.1.64" >> $GITHUB_OUTPUT
          else
            echo "emscripten=4.0.11" >> $GITHUB_OUTPUT
          fi

      - name: Set up Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{ steps.versions.outputs.emscripten }}
          no-cache: true

      - name: Verify Emscripten setup
        run: |
          emcc -v

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        with:
          cache-name: ${{ steps.name.outputs.name }}
        continue-on-error: true

      - name: Setup Python and SCons
        uses: ./.github/actions/godot-deps

      - name: Compilation [4.4]
        if: inputs.version == '4.4'
        uses: ./.github/actions/godot-build
        with:
          sconsflags: >-
            ${{ env.SCONSFLAGS }}             
            ${{ matrix.engine == 'qjs-ng' && 'use_quickjs_ng=yes' || '' }}
          platform: web
          target: ${{ matrix.target }}
          scons-cache-limit: 0.5

      - name: Compilation [4.5+]
        if: inputs.version != '4.4'
        uses: ./.github/actions/godot-build
        with:
          scons-flags: >-
            ${{ env.SCONS_FLAGS }}             
            ${{ matrix.engine == 'qjs-ng' && 'use_quickjs_ng=yes' || '' }}
          platform: web
          target: ${{ matrix.target }}

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: ${{ steps.name.outputs.name }}
        continue-on-error: true

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ steps.name.outputs.name }}
