name: ðŸ”„ Changesets
on:
  workflow_call:
    outputs:
      publish:
        description: "Should publish"
        value: ${{ jobs.changesets.outputs.publish || 'false' }}

permissions:
  contents: write
  pull-requests: write

jobs:
  changesets:
    name: ðŸ”„ Changesets
    runs-on: ubuntu-latest
    outputs:
      publish: ${{ steps.should_publish.outputs.publish }}
    steps:
      - name: â¬ Checkout repository
        uses: actions/checkout@v4

      - name: ðŸ›« Setup pnpm
        uses: ./.github/actions/pnpm-setup

      - name: ðŸ› ï¸ Install dependencies
        run: |
          pnpm install

      - name: ðŸ†š Create and publish versions
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore: update versions"
          title: "chore: update versions"
          version: pnpm ci:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: â“ Should publish
        id: should_publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HAS_CHANGESETS: ${{ steps.changesets.outputs.hasChangesets }}
        run: |
          SHOULD_PUBLISH=$(pnpm run ci:should-publish)
          if [[ $SHOULD_PUBLISH == "true" && $HAS_CHANGESETS == "false" ]]; then
            echo "publish=true" >> $GITHUB_OUTPUT
          else
            echo "publish=false" >> $GITHUB_OUTPUT
          fi
