name: ğŸ”¬ Test editor
on:
  workflow_call:


jobs:
  test-editor:
    name: ğŸ”¬ Test editor
    runs-on: ubuntu-latest
    steps:
      - name: â¬ Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ›« Setup pnpm
        uses: ./.github/actions/pnpm-setup

      - name: ğŸ› ï¸ Install dependencies
        run: |
          pnpm install
          pnpm test
